header_pages:
  - index.md
  - projects.md

remote_theme: b2a3e8/jekyll-theme-console
title: Home Page
author: Jean-Sebastien Prenovost
plugins:
  - jekyll-remote-theme
description: Welcome to my github page :)
